#!/usr/bin/env bash
# Configures a new ubuntu machine
# Install Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

# Update and Install Nginx
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y


# start nginx service
echo -e "\nStarting Nginx service.\n"
sudo service nginx start

# allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# set the user ownership and permissions for website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Sett up and redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

echo -e "\nConfiguration Completed.\n"
