#!/usr/bin/env bash
# Custmizes a 404-error_page

# Updates Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creates an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performs a "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creates a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Creates an HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Tests configurations for syntax errors
sudo nginx -t

# Restarts nginx after implementing changes
sudo service nginx restart
